{% set name = "napari-trackpy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-trackpy-{{ version }}.tar.gz
  sha256: fcbdc8cbd7cc031fcea244627617f97c10f2b655df301229e4cb2c4eab832c85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - setuptools-scm
    - wheel
  run:
    - magicgui
    - matplotlib-base
    - napari
    - napari-aicsimageio >=0.7.0
    - numpy
    - python >={{ python_min }}
    - qtpy
    - superqt
    - trackpy

test:
  imports:
    - napari_trackpy
  commands:
    - pip list
    # - pip check # Fails due to aicsimageio dependencies
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-trackpy
  summary: Plugin to do trackpy particle tracking on microscopy data within napari
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rhoitink/napari-trackpy

extra:
  recipe-maintainers:
    - goanpeca
    - rhoitink
